import "@portfolio/app/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
// import Script from "next/script";
// import Navbar from "@portfolio/components/navbar";
// import Footer from "@portfolio/components/footer";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>GrumpyTofu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}
export default MyApp;
