export default function Head() {
  return (
    <>
      <title>GrumpyTofu</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src https://*; child-src 'none'; vitals.vercel-insights.com;" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
