import Head from "next/head";
import Image from "next/image";
import grumpyTofu from '../public/grumpytofu.webp';

export default function Home() {
  return (
    <>
      <Head>
        <title>GrumpyTofu | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Image src={grumpyTofu} alt="Picture of the author" />
      </div>
    </>
  );
}
