import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
//import grumpyTofu from "../public/grumpytofu.png";
import nextStream from "../public/next-stream.webp";
import nextTube from "../public/next-tube.webp";

interface Project {
  image: StaticImageData;
  text: string;
  url: string;
}

const projects: Project[] = [
  {
    image: nextStream,
    text: "Next Stream",
    url: "https://next-stream-five.vercel.app/",
  },
  {
    image: nextTube,
    text: "Next Tube",
    url: "https://next-tube.vercel.app/",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>GrumpyTofu | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col w-full justify-center overflow-y-hidden">
        <div style={{ minHeight: "70vh" }}>
          <h1 className="my-4 text-3xl md:text-5xl text-white opacity-75 font-bold leading-tight text-center">
            Grumpy
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-green-400 via-pink-500 to-purple-500">Tofu</span>
          </h1>
          <p className="leading-normal text-base md:text-2xl mb-8 text-center">Welcome to my slice of the internet!</p>
        </div>

        <div className="w-full bg-custom-dark-purple rounded-lg p-5">
          <h2 className="my-4 text-3xl md:text-5xl text-white opacity-75 font-bold leading-tight underline text-center pb-4">Projects</h2>
          <div className="w-full">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
              {projects.map((project) => (
                <div key={project.url}>
                  <a href={project.url} target="_blank" rel="noreferrer">
                    <div className="transform-gpu duration-300 hover:scale-105">
                      <Image src={project.image} alt={`${project.text} project image`} layout="responsive" height={300} width={500} />
                    </div>
                  </a>
                  <p className="text-xl text-white p-2">{project.text}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="w-full bg-custom-blue rounded-lg p-5">
          <h2 className="my-4 text-3xl md:text-5xl text-white opacity-75 font-bold leading-tight underline text-center pb-4">Blog</h2>
          <p className="text-white text-center my-10">Here is where I will post some note-worthy content!</p>
          <div className="w-full flex justify-center align-middle mb-10">
            <Link href="/blog">
              <a className="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow">Blog</a>
            </Link>
          </div>
        </div>
      </div>
    </>
  );
}
