import Head from "next/head";
import Image from "next/image";
import grumpyTofu from "../public/grumpytofu.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>GrumpyTofu | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col h-full w-full">
        <div className="flex justify-center">
          <div className="max-w-md">
            <Image src={grumpyTofu} alt="Picture of the author" />
          </div>
        </div>
        <p className="text-center text-black dark:text-white">This website is currently under construction</p>
      </div>
    </>
  );
}
